import jsPDF from 'jspdf';

interface SlipData {
  fullName: string;
  matriculationNumber: string;
  institution: string;
  faculty: string;
  department: string;
  programmeCategory: string;
  programmeType: string;
  projectTitle: string;
  approvalDate: string;
}

export function generateApprovedSlip(data: SlipData) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 30;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('NERD ASSIST', pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Student Registration & Project Management', pageWidth / 2, y, { align: 'center' });
  y += 12;

  // Horizontal rule
  doc.setDrawColor(34, 139, 34);
  doc.setLineWidth(1);
  doc.line(20, y, pageWidth - 20, y);
  y += 14;

  // Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(34, 139, 34);
  doc.text('APPROVAL SLIP', pageWidth / 2, y, { align: 'center' });
  y += 14;
  doc.setTextColor(0, 0, 0);

  // Body
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const bodyText = `This is to certify that the registration and payment submitted by the student named below has been reviewed and APPROVED.`;
  const bodyLines = doc.splitTextToSize(bodyText, pageWidth - 50);
  doc.text(bodyLines, 25, y);
  y += bodyLines.length * 7 + 10;

  // Student details
  const fields: [string, string][] = [
    ['Full Name', data.fullName],
    ['Matriculation Number', data.matriculationNumber],
    ['Institution', data.institution],
    ['Faculty', data.faculty],
    ['Department', data.department],
    ['Programme', `${data.programmeCategory} — ${data.programmeType}`],
    ['Project Title', data.projectTitle],
    ['Approval Date', data.approvalDate],
  ];

  for (const [label, value] of fields) {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, 25, y);
    doc.setFont('helvetica', 'normal');
    const valueLines = doc.splitTextToSize(value, pageWidth - 95);
    doc.text(valueLines, 80, y);
    y += valueLines.length * 7 + 3;
  }

  y += 15;

  // Stamp area
  doc.setDrawColor(34, 139, 34);
  doc.setLineWidth(0.5);
  doc.roundedRect(pageWidth / 2 - 35, y, 70, 25, 3, 3);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(34, 139, 34);
  doc.text('APPROVED', pageWidth / 2, y + 15, { align: 'center' });
  doc.setTextColor(0, 0, 0);

  y += 40;

  // Footer line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(20, y, pageWidth - 20, y);
  y += 8;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.text('This document is auto-generated by Nerd Assist Admin.', pageWidth / 2, y, { align: 'center' });

  // Download
  const filename = `Approved_Slip_${data.fullName.replace(/\s+/g, '_')}.pdf`;
  doc.save(filename);
}
